#!/usr/bin/env python3
"""Read / train rank JSONL from pack3d --rank-dump.

Usage:
  python3 train_rank.py stats rank.jsonl
  python3 train_rank.py train rank.jsonl -o rank_weights.h
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable

RANK_DIM = 28
DEFAULT_SCALE = 10_000.0
NAMES = [
    "fill", "nplaced", "floor_cover", "maxz_h", "origin_used", "minx_w", "miny_d",
    "maxx_w", "maxy_d", "wall_contact", "item_contact", "nems", "nep", "max_cav_vol",
    "sum_usable_cav", "dead_cav", "max_cav_w", "max_cav_d", "max_cav_h", "pending_n",
    "pending_top4_v", "pending_top4_e", "unplaceable", "compactness", "last_lbb",
    "last_waste", "last_hm", "last_walls",
]

Phi = list[float]
Pair = tuple[Phi, Phi]


def sigmoid(x: float) -> float:
    if x >= 0:
        z = math.exp(-x)
        return 1.0 / (1.0 + z)
    z = math.exp(x)
    return z / (1.0 + z)


def dot(a: list[float], b: list[float]) -> float:
    return sum(x * y for x, y in zip(a, b))


def sub(a: Phi, b: Phi) -> Phi:
    return [x - y for x, y in zip(a, b)]


def check_phi(phi: list, ctx: str) -> Phi:
    if len(phi) != RANK_DIM:
        raise SystemExit(f"{ctx}: bad phi len {len(phi)}, expected {RANK_DIM}")
    return [float(x) for x in phi]


def load_pairs(path: Path, from_cands: bool) -> tuple[list[Pair], int, int, Counter]:
    """Return (pairs, ncand, npair_lines, kept_counter)."""
    pairs: list[Pair] = []
    nc = 0
    npair_lines = 0
    kept = Counter()
    groups: dict[tuple, list[tuple[int, Phi, int]]] = defaultdict(list)

    with path.open(encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            row = json.loads(line)
            t = row.get("type")
            if t == "cand":
                nc += 1
                kept[row["kept"]] += 1
                phi = check_phi(row["phi"], f"line {line_no}")
                key = (row["bin"], row["layer"], row["g"], row["nplaced"])
                groups[key].append((row["rank"], phi, row["kept"]))
            elif t == "pair":
                npair_lines += 1
                pa = check_phi(row["phi_a"], f"line {line_no} phi_a")
                pb = check_phi(row["phi_b"], f"line {line_no} phi_b")
                pairs.append((pa, pb))

    if from_cands or len(pairs) == 0:
        for items in groups.values():
            if len(items) < 2:
                continue
            best_kept: tuple[int, Phi] | None = None
            best_reject: tuple[int, Phi] | None = None
            for rank, phi, k in items:
                if k:
                    if best_kept is None or rank > best_kept[0]:
                        best_kept = (rank, phi)
                elif best_reject is None or rank > best_reject[0]:
                    best_reject = (rank, phi)
            if best_kept and best_reject:
                pairs.append((best_kept[1], best_reject[1]))

    return pairs, nc, npair_lines, kept


def cmd_stats(path: Path, from_cands: bool) -> None:
    if not path.is_file():
        raise SystemExit(f"missing {path}; run: ./pack3d 8 --rank-dump {path} < input.txt")
    pairs, nc, npair_lines, kept = load_pairs(path, from_cands=from_cands)
    print(f"file: {path}")
    print(f"candidates: {nc}  pair lines: {npair_lines}  trainable pairs: {len(pairs)}")
    print(f"kept ratio: {kept[1]}/{nc or 1}")
    print(f"features ({RANK_DIM}): {', '.join(NAMES)}")


def pair_accuracy(pairs: Iterable[Pair], w: list[float], bias: float) -> float:
    ok = tot = 0
    for pa, pb in pairs:
        z = bias + dot(w, sub(pa, pb))
        tot += 1
        if z >= 0:
            ok += 1
    return ok / max(1, tot)


def train_pairwise(
    pairs: list[Pair],
    *,
    epochs: int,
    lr: float,
    reg: float,
    seed: int,
) -> tuple[list[float], float]:
    rng = random.Random(seed)
    w = [0.0] * RANK_DIM
    bias = 0.0
    n = len(pairs)
    if n == 0:
        raise SystemExit("no training pairs; run pack3d with --rank-dump on real input (beam=480)")

    idx = list(range(n))
    for _ in range(epochs):
        rng.shuffle(idx)
        for i in idx:
            pa, pb = pairs[i]
            x = sub(pa, pb)
            z = bias + dot(w, x)
            err = sigmoid(z) - 1.0  # label: a beats b
            for j in range(RANK_DIM):
                w[j] -= lr * (err * x[j] + reg * w[j])
            bias -= lr * err
    return w, bias


def write_rank_weights_h(
    path: Path,
    w: list[float],
    bias: float,
    scale: float,
    *,
    npairs: int,
    train_acc: float,
    val_acc: float | None,
) -> None:
    lines = [
        "#pragma once",
        "",
        "// Generated by train_rank.py — do not edit.",
        f"// pairs={npairs} train_acc={train_acc:.4f}"
        + (f" val_acc={val_acc:.4f}" if val_acc is not None else ""),
        "",
        f"inline constexpr int RANK_LEARNED_DIM = {RANK_DIM};",
        f"inline constexpr float RANK_LEARNED_SCALE = {scale:.1f}f;",
        f"inline constexpr float RANK_LEARNED_BIAS = {bias:.8f}f;",
        "",
        "inline constexpr float RANK_LEARNED_W[RANK_LEARNED_DIM] = {",
    ]
    for i, wi in enumerate(w):
        comma = "," if i + 1 < RANK_DIM else ""
        lines.append(f"    {wi:+.8f}f{comma}  // {NAMES[i]}")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def cmd_train(
    path: Path,
    out: Path,
    *,
    scale: float,
    epochs: int,
    lr: float,
    reg: float,
    val_frac: float,
    seed: int,
    from_cands: bool,
) -> None:
    if not path.is_file():
        raise SystemExit(f"missing {path}; run: ./pack3d 8 --rank-dump {path} < input.txt")
    pairs, nc, npair_lines, kept = load_pairs(path, from_cands=from_cands)
    if len(pairs) < 8:
        raise SystemExit(
            f"only {len(pairs)} pairs (cands={nc}, pair_lines={npair_lines}); "
            "need a full --rank-dump run (beam=480, full input)"
        )

    rng = random.Random(seed)
    rng.shuffle(pairs)
    n_val = max(1, int(len(pairs) * val_frac)) if len(pairs) >= 20 else 0
    val_pairs = pairs[:n_val]
    train_pairs = pairs[n_val:]

    w, bias = train_pairwise(train_pairs, epochs=epochs, lr=lr, reg=reg, seed=seed)
    train_acc = pair_accuracy(train_pairs, w, bias)
    val_acc = pair_accuracy(val_pairs, w, bias) if val_pairs else None

    write_rank_weights_h(
        out,
        w,
        bias,
        scale,
        npairs=len(pairs),
        train_acc=train_acc,
        val_acc=val_acc,
    )

    print(f"file: {path}")
    print(f"candidates: {nc}  pair lines: {npair_lines}  pairs used: {len(pairs)}")
    print(f"kept ratio: {kept[1]}/{nc or 1}")
    print(f"train pairs: {len(train_pairs)}  val pairs: {len(val_pairs)}")
    print(f"pair accuracy: train={train_acc:.4f}" + (f" val={val_acc:.4f}" if val_acc is not None else ""))
    print(f"weights -> {out}")
    print()
    print("top |w| features:")
    order = sorted(range(RANK_DIM), key=lambda i: abs(w[i]), reverse=True)
    for i in order[:8]:
        print(f"  {NAMES[i]:16s}  w={w[i]:+.6f}")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Rank JSONL stats / pairwise logistic training.")
    sub = p.add_subparsers(dest="cmd")

    ps = sub.add_parser("stats", help="count cands/pairs and validate phi (default)")
    ps.add_argument("jsonl", nargs="?", default="rank.jsonl", type=Path)
    ps.add_argument(
        "--from-cands",
        action="store_true",
        help="also count pairs reconstructable from cand groups",
    )

    pt = sub.add_parser("train", help="pairwise logistic -> rank_weights.h")
    pt.add_argument("jsonl", type=Path)
    pt.add_argument("-o", "--out", default="rank_weights.h", type=Path)
    pt.add_argument("--scale", type=float, default=DEFAULT_SCALE, help="C++ tie-break scale")
    pt.add_argument("--epochs", type=int, default=40)
    pt.add_argument("--lr", type=float, default=0.08)
    pt.add_argument("--reg", type=float, default=1e-3, help="L2 on weights")
    pt.add_argument("--val-frac", type=float, default=0.15)
    pt.add_argument("--seed", type=int, default=0)
    pt.add_argument(
        "--from-cands",
        action="store_true",
        help="rebuild pairs from cand kept/reject if pair lines are sparse",
    )
    return p


def main(argv: list[str] | None = None) -> None:
    argv = argv if argv is not None else sys.argv[1:]
    if not argv:
        argv = ["stats", "rank.jsonl"]
    elif argv[0] not in ("stats", "train"):
        argv = ["stats", *argv]

    args = build_parser().parse_args(argv)
    if args.cmd == "stats":
        cmd_stats(args.jsonl, from_cands=args.from_cands)
    else:
        cmd_train(
            args.jsonl,
            args.out,
            scale=args.scale,
            epochs=args.epochs,
            lr=args.lr,
            reg=args.reg,
            val_frac=args.val_frac,
            seed=args.seed,
            from_cands=args.from_cands,
        )


if __name__ == "__main__":
    main()
